### ISSUE TITLE
Only the first entry form is exported

### ISSUE THREAD

**Issue by ajoah** [codelight-eu/gdpr-for-gravity-forms#1]
Hi,

I'm testing your plugin and i found a problem : it exports only the first entry found by form.

It is because of an array key in your code which is the same for all entries (so the last entry overrides the others).

See : https://github.com/codelight-eu/gdpr-for-gravity-forms/blob/243998e8ce4dff3aca8674a4f21a95081014478e/src/GravityForms.php#L50-L62

The `$title` variable is the same for all entries.

**Comment by indrek-k** [comment]
Thanks so much for tracking down the issue! Will fix this ASAP.

**Comment by teolaz** [comment]
Saw you fixed the source code, but not updated version on WP plugin trac...
could you do that please?

**Comment by indrek-k** [comment]
Updated the plugin in WP repo. Also, the usage of the word "ASAP" is now banned from my vocabulary. 

Sorry about the delay, I've been unbelievably busy :|

**Comment by teolaz** [comment]
>  Also, the usage of the word "ASAP" is now banned from my vocabulary.

Lol, thanks for this one, it makes me happy this morning!
Gonna help you with the framework **as soon as i have time** :-)
